#!/bin/ksh
# This shell script (makefw) creates the Firmware
#  Update Diskette, Version 1.11 for the RS/6000
#  43P Model 120/133 (type 7248) system.
#
echo "dd if=./fw-111.dd of=/dev/rfd0 obs=90b conv=sync"
dd if=./fw-111.dd of=/dev/rfd0 obs=90b conv=sync
if [ $? -eq 0 ]
 then
    echo "Remove the diskette.  Please label it "
    echo " \"IBM RS/6000 43P Model 120/133"
    echo "  Firmware Update Diskette Version 1.11\""
  else
    echo "Diskette not successfully created".
fi
